var ikarusWidgetAirports = {
  "AFL": {
    "id": "112",
    "acronym": "AFL",
    "name": "Alta Floresta (AFL)",
    "nick": "Alta Floresta",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "AFL",
    "latitude": "-9.865396",
    "longitude": "-56.105927"
  },
  "ATM": {
    "id": "111",
    "acronym": "ATM",
    "name": "Altamira (ATM)",
    "nick": "Altamira",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "ATM",
    "latitude": "-3.2513635",
    "longitude": "-52.251643"
  },
  "AMS": {
    "id": "175",
    "acronym": "AMS",
    "name": "Amsterdam (AMS)",
    "nick": "Amsterdam",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "AMS",
    "latitude": "52.3105392",
    "longitude": "4.7682743"
  },
  "ANF": {
    "id": "143",
    "acronym": "ANF",
    "name": "Antofagasta (ANF)",
    "nick": "Antofagasta",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ANF",
    "latitude": "-23.449",
    "longitude": "-70.44079"
  },
  "AJU": {
    "id": "110",
    "acronym": "AJU",
    "name": "Aracaju (AJU)",
    "nick": "Aracaju",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "AJU",
    "latitude": "-10.984643",
    "longitude": "-37.0706779"
  },
  "ARU": {
    "id": "109",
    "acronym": "ARU",
    "name": "Aracatuba (ARU)",
    "nick": "Aracatuba",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "ARU",
    "latitude": "-21.1379689",
    "longitude": "-50.4264508"
  },
  "AUX": {
    "id": "108",
    "acronym": "AUX",
    "name": "Araguaina (AUX)",
    "nick": "Araguaina",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "AUX",
    "latitude": "-7.2274822",
    "longitude": "-48.2392688"
  },
  "AAX": {
    "id": "106",
    "acronym": "AAX",
    "name": "Araxa (AAX)",
    "nick": "Araxa",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "AAX",
    "latitude": "-19.5594639",
    "longitude": "-46.9651795"
  },
  "AQP": {
    "id": "187",
    "acronym": "AQP",
    "name": "Arequipa (AQP)",
    "nick": "Arequipa",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "AQP",
    "latitude": "-16.344812",
    "longitude": "-71.567989"
  },
  "ARI": {
    "id": "145",
    "acronym": "ARI",
    "name": "Arica (ARI)",
    "nick": "Arica",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ARI",
    "latitude": "-18.3486109",
    "longitude": "-70.338611"
  },
  "AUA": {
    "id": "232",
    "acronym": "AUA",
    "name": "Aruba (AUA)",
    "nick": "Aruba",
    "azul": false,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "AUA",
    "latitude": "12.5015939",
    "longitude": "-70.0119926"
  },
  "ASU": {
    "id": "195",
    "acronym": "ASU",
    "name": "Assuncao (ASU)",
    "nick": "Assuncao",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "ASU",
    "latitude": "-25.239722",
    "longitude": "-57.519167"
  },
  "ATL": {
    "id": "224",
    "acronym": "ATL",
    "name": "Atlanta (ATL)",
    "nick": "Atlanta",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "ATL",
    "latitude": "33.639975",
    "longitude": "-84.444032"
  },
  "AUS": {
    "id": "223",
    "acronym": "AUS",
    "name": "Austin (AUS)",
    "nick": "Austin",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "AUS",
    "latitude": "30.202633",
    "longitude": "-97.668146"
  },
  "BBA": {
    "id": "142",
    "acronym": "BBA",
    "name": "Balmaceda (BBA)",
    "nick": "Balmaceda",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "BBA",
    "latitude": "-45.916389",
    "longitude": "-71.686944"
  },
  "BGI": {
    "id": "233",
    "acronym": "BGI",
    "name": "Barbados (BGI)",
    "nick": "Barbados",
    "azul": false,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "BGI",
    "latitude": "13.075418",
    "longitude": "-59.493768"
  },
  "BAZ": {
    "id": "246",
    "acronym": "BAZ",
    "name": "Barcelos (BAZ)",
    "nick": "Barcelos",
    "azul": true,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "BAZ",
    "latitude": "-0.9756045",
    "longitude": "-62.9175264"
  },
  "BRA": {
    "id": "105",
    "acronym": "BRA",
    "name": "Barreiras (BRA)",
    "nick": "Barreiras",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "BRA",
    "latitude": "-12.079561",
    "longitude": "-45.010035"
  },
  "JTC": {
    "id": "104",
    "acronym": "JTC",
    "name": "Bauru (JTC)",
    "nick": "Bauru",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "JTC",
    "latitude": "-22.1576101",
    "longitude": "-49.0717704"
  },
  "BEL": {
    "id": "103",
    "acronym": "BEL",
    "name": "Belem (BEL)",
    "nick": "Val-de-Cans",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BEL",
    "latitude": "-1.3820615",
    "longitude": "-48.4775227"
  },
  "CNF": {
    "id": "102",
    "acronym": "CNF",
    "name": "Belo Horizonte - Confins Intl (CNF)",
    "nick": "Confins",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "CNF",
    "latitude": "-19.634099",
    "longitude": "-43.965396"
  },
  "PLU": {
    "id": "101",
    "acronym": "PLU",
    "name": "Belo Horizonte - Pampulha (PLU)",
    "nick": "Pampulha",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "PLU",
    "latitude": "-19.8498475",
    "longitude": "-43.9548899"
  },
  "BHZ": {
    "id": "100",
    "acronym": "BHZ",
    "name": "Belo Horizonte - Todos (BHZ)",
    "nick": "Belo Horizonte - Todos",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BHZ,PLU,CNF",
    "latitude": null,
    "longitude": null
  },
  "TXL": {
    "id": "157",
    "acronym": "TXL",
    "name": "Berlim Berlin-Tegel Intl (TXL)",
    "nick": "Berlim Berlin-Tegel Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "TXL",
    "latitude": "52.5588327",
    "longitude": "13.2884374"
  },
  "BVB": {
    "id": "99",
    "acronym": "BVB",
    "name": "Boa Vista (BVB)",
    "nick": "Boa Vista",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BVB",
    "latitude": "2.8429648",
    "longitude": "-60.6911105"
  },
  "BOG": {
    "id": "147",
    "acronym": "BOG",
    "name": "Bogota (BOG)",
    "nick": "Bogota",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "BOG",
    "latitude": "4.7007444",
    "longitude": "-74.1445487"
  },
  "BYO": {
    "id": "98",
    "acronym": "BYO",
    "name": "Bonito (BYO)",
    "nick": "Bonito",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "BYO",
    "latitude": "-21.1265489",
    "longitude": "-56.4840784"
  },
  "BOS": {
    "id": "222",
    "acronym": "BOS",
    "name": "Boston Logan Intl (BOS)",
    "nick": "Boston Logan Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "BOS",
    "latitude": "42.3656132",
    "longitude": "-71.0095602"
  },
  "BSB": {
    "id": "97",
    "acronym": "BSB",
    "name": "Brasilia (BSB)",
    "nick": "Brasilia",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BSB",
    "latitude": "-15.8697369",
    "longitude": "-47.9172348"
  },
  "BRE": {
    "id": "155",
    "acronym": "BRE",
    "name": "Bremen (BRE)",
    "nick": "Bremen",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "BRE",
    "latitude": "53.0479741",
    "longitude": "8.7858793"
  },
  "BRU": {
    "id": "12",
    "acronym": "BRU",
    "name": "Bruxelas (BRU)",
    "nick": "Bruxelas",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "BRU",
    "latitude": "50.900999",
    "longitude": "4.4855744"
  },
  "AEP": {
    "id": "10",
    "acronym": "AEP",
    "name": "Buenos Aires Aeroparque (AEP)",
    "nick": "Buenos Aires - Aeroparque",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "AEP",
    "latitude": "-34.5580305",
    "longitude": "-58.4170088"
  },
  "EZE": {
    "id": "8",
    "acronym": "EZE",
    "name": "Buenos Aires Ezeiza Intl (EZE)",
    "nick": "Buenos Aires",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "EZE",
    "latitude": "-34.822491",
    "longitude": "-58.5349216"
  },
  "BUE": {
    "id": "9",
    "acronym": "BUE",
    "name": "Buenos Aires Todos (BUE)",
    "nick": "Buenos Aires Todos",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BUE,EZE,AEP",
    "latitude": null,
    "longitude": null
  },
  "CFB": {
    "id": "243",
    "acronym": "CFB",
    "name": "Cabo Frio (CFB)",
    "nick": "Cabo Frio",
    "azul": true,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "CFB",
    "latitude": "-22.921599",
    "longitude": "-42.0730019"
  },
  "OAL": {
    "id": "95",
    "acronym": "OAL",
    "name": "Cacoal (OAL)",
    "nick": "Cacoal",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "OAL",
    "latitude": "-11.432844",
    "longitude": "-61.4777"
  },
  "CJC": {
    "id": "141",
    "acronym": "CJC",
    "name": "Calama (CJC)",
    "nick": "Calama",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CJC",
    "latitude": "-22.495085",
    "longitude": "-68.90843"
  },
  "CLV": {
    "id": "247",
    "acronym": "CLV",
    "name": "Caldas Novas (CLV)",
    "nick": "Caldas Novas",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "CLV",
    "latitude": "-17.7262885",
    "longitude": "-48.6094894"
  },
  "YYC": {
    "id": "127",
    "acronym": "YYC",
    "name": "Calgary (YYC)",
    "nick": "Calgary",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YYC",
    "latitude": "51.131471",
    "longitude": "-114.010556"
  },
  "CPV": {
    "id": "234",
    "acronym": "CPV",
    "name": "Campina Grande (CPV)",
    "nick": "Campina Grande",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "CPV",
    "latitude": "-7.2696016",
    "longitude": "-35.897396"
  },
  "VCP": {
    "id": "26",
    "acronym": "VCP",
    "name": "Campinas Viracopos (VCP)",
    "nick": "Viracopos",
    "azul": true,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "VCP,CPQ",
    "latitude": "-23.008205",
    "longitude": "-47.1375685"
  },
  "CGR": {
    "id": "94",
    "acronym": "CGR",
    "name": "Campo Grande (CGR)",
    "nick": "Campo Grande",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "CGR",
    "latitude": "-20.4686937",
    "longitude": "-54.6741233"
  },
  "CAW": {
    "id": "118",
    "acronym": "CAW",
    "name": "Campos dos Goytacazes (CAW)",
    "nick": "Campos dos Goytacazes",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "CAW",
    "latitude": "-21.701775",
    "longitude": "-41.3069137"
  },
  "CCS": {
    "id": "231",
    "acronym": "CCS",
    "name": "Caracas (CCS)",
    "nick": "Caracas",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "CCS",
    "latitude": "10.60213",
    "longitude": "-66.9955389"
  },
  "CKS": {
    "id": "93",
    "acronym": "CKS",
    "name": "Carajas (CKS)",
    "nick": "Carajas",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "CKS",
    "latitude": "-6.117568",
    "longitude": "-50.001089"
  },
  "CAC": {
    "id": "92",
    "acronym": "CAC",
    "name": "Cascavel (CAC)",
    "nick": "Cascavel",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "CAC",
    "latitude": "-25.0006926",
    "longitude": "-53.5011274"
  },
  "CXJ": {
    "id": "235",
    "acronym": "CXJ",
    "name": "Caxias do Sul (CXJ)",
    "nick": "Caxias do Sul",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "CXJ",
    "latitude": "-29.1954367",
    "longitude": "-51.18868510000001"
  },
  "XAP": {
    "id": "91",
    "acronym": "XAP",
    "name": "Chapeco (XAP)",
    "nick": "Chapeco",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "XAP",
    "latitude": "-27.1341698",
    "longitude": "-52.6569128"
  },
  "ORD": {
    "id": "221",
    "acronym": "ORD",
    "name": "Chicago O`Hare Intl (ORD)",
    "nick": "Chicago O`Hare Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "ORD",
    "latitude": "41.9741625",
    "longitude": "-87.9073214"
  },
  "CIX": {
    "id": "186",
    "acronym": "CIX",
    "name": "Chiclayo (CIX)",
    "nick": "Chiclayo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CIX",
    "latitude": "-6.787222",
    "longitude": "-79.828056"
  },
  "MEX": {
    "id": "174",
    "acronym": "MEX",
    "name": "Cidade do Mexico (MEX)",
    "nick": "Cidade do Mexico",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "MEX",
    "latitude": "19.436111",
    "longitude": "-99.071944"
  },
  "AGT": {
    "id": "194",
    "acronym": "AGT",
    "name": "Ciudad del Leste (AGT)",
    "nick": "Ciudad del Leste",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "AGT",
    "latitude": "-25.4555",
    "longitude": "-54.843592"
  },
  "CLE": {
    "id": "220",
    "acronym": "CLE",
    "name": "Cleveland Hopkins Intl (CLE)",
    "nick": "Cleveland Hopkins Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "CLE",
    "latitude": "41.411675",
    "longitude": "-81.834693"
  },
  "CIZ": {
    "id": "248",
    "acronym": "CIZ",
    "name": "Coari (CIZ)",
    "nick": "Coari",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "CIZ",
    "latitude": "-4.0944897",
    "longitude": "-63.1446104"
  },
  "CRD": {
    "id": "7",
    "acronym": "CRD",
    "name": "Comodoro Rivadavia (CRD)",
    "nick": "Comodoro Rivadavia",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CRD",
    "latitude": "-45.785278",
    "longitude": "-67.465556"
  },
  "CCP": {
    "id": "140",
    "acronym": "CCP",
    "name": "Concepcion (CCP)",
    "nick": "Concepcion",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CCP",
    "latitude": "-36.7720244",
    "longitude": "-73.0601099"
  },
  "CPH": {
    "id": "158",
    "acronym": "CPH",
    "name": "Copenhagen (CPH)",
    "nick": "Copenhagen",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CPH",
    "latitude": "55.6180236",
    "longitude": "12.6507628"
  },
  "CPO": {
    "id": "139",
    "acronym": "CPO",
    "name": "Copiapo (CPO)",
    "nick": "Copiapo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CPO",
    "latitude": "-27.296667",
    "longitude": "-70.413611"
  },
  "COR": {
    "id": "6",
    "acronym": "COR",
    "name": "Cordoba (COR)",
    "nick": "Cordoba",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "COR",
    "latitude": "-31.3137926",
    "longitude": "-64.2101332"
  },
  "CMG": {
    "id": "90",
    "acronym": "CMG",
    "name": "Corumba (CMG)",
    "nick": "Corumba",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "CMG",
    "latitude": "-19.0114361",
    "longitude": "-57.6642951"
  },
  "CCM": {
    "id": "89",
    "acronym": "CCM",
    "name": "Criciuma (CCM)",
    "nick": "Criciuma",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "CCM",
    "latitude": "-28.7254793",
    "longitude": "-49.4236346"
  },
  "CZS": {
    "id": "117",
    "acronym": "CZS",
    "name": "Cruzeiro do Sul (CZS)",
    "nick": "Cruzeiro do Sul",
    "azul": false,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "CZS",
    "latitude": "-7.5983492",
    "longitude": "-72.7734275"
  },
  "CGB": {
    "id": "88",
    "acronym": "CGB",
    "name": "Cuiaba (CGB)",
    "nick": "Cuiaba",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "CGB",
    "latitude": "-15.6530786",
    "longitude": "-56.1172687"
  },
  "CWB": {
    "id": "87",
    "acronym": "CWB",
    "name": "Curitiba (CWB)",
    "nick": "Curitiba",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "CWB",
    "latitude": "-25.5327132",
    "longitude": "-49.1724811"
  },
  "CUZ": {
    "id": "185",
    "acronym": "CUZ",
    "name": "Cuzco (CUZ)",
    "nick": "Cuzco",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CUZ",
    "latitude": "-13.5380263",
    "longitude": "-71.9436497"
  },
  "DFW": {
    "id": "218",
    "acronym": "DFW",
    "name": "Dallas Fort Worth Intl (DFW)",
    "nick": "Dallas Fort Worth Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "DFW",
    "latitude": "32.8998091",
    "longitude": "-97.0403352"
  },
  "DEN": {
    "id": "217",
    "acronym": "DEN",
    "name": "Denver (DEN)",
    "nick": "Denver",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "DEN",
    "latitude": "39.8495117",
    "longitude": "-104.6737193"
  },
  "DOU": {
    "id": "86",
    "acronym": "DOU",
    "name": "Dourados (DOU)",
    "nick": "Dourados",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "DOU",
    "latitude": "-22.1974185",
    "longitude": "-54.9259758"
  },
  "DUS": {
    "id": "154",
    "acronym": "DUS",
    "name": "Dusseldorf (DUS)",
    "nick": "Dusseldorf",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "DUS",
    "latitude": "51.2827846",
    "longitude": "6.7622701"
  },
  "EGE": {
    "id": "199",
    "acronym": "EGE",
    "name": "Eagle County-Vail (EGE)",
    "nick": "Eagle County-Vail",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "EGE",
    "latitude": "39.6425",
    "longitude": "-106.9175"
  },
  "YEG": {
    "id": "126",
    "acronym": "YEG",
    "name": "Edmonton (YEG)",
    "nick": "Edmonton",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YEG",
    "latitude": "53.308035",
    "longitude": "-113.583768"
  },
  "ERN": {
    "id": "249",
    "acronym": "ERN",
    "name": "Eirunepe (ERN)",
    "nick": "Eirunepe",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "ERN",
    "latitude": "-6.6571401",
    "longitude": "-69.8667141"
  },
  "FTE": {
    "id": "5",
    "acronym": "FTE",
    "name": "El Calafate (FTE)",
    "nick": "El Calafate",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "FTE",
    "latitude": "-50.2832802",
    "longitude": "-72.0550722"
  },
  "ESR": {
    "id": "138",
    "acronym": "ESR",
    "name": "El Salvador (ESR)",
    "nick": "El Salvador",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ESR",
    "latitude": "-26.3112876",
    "longitude": "-69.7741153"
  },
  "ARN": {
    "id": "197",
    "acronym": "ARN",
    "name": "Estocolmo (ARN)",
    "nick": "Estocolmo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "ARN",
    "latitude": "59.6497622",
    "longitude": "17.9237807"
  },
  "STO": {
    "id": "196",
    "acronym": "STO",
    "name": "Estocolmo (STO)",
    "nick": "Estocolmo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "STO",
    "latitude": "59.354812",
    "longitude": "17.9427216"
  },
  "FAO": {
    "id": "193",
    "acronym": "FAO",
    "name": "Faro (FAO)",
    "nick": "Faro",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "FAO",
    "latitude": "37.0175956",
    "longitude": "-7.96972"
  },
  "FEN": {
    "id": "84",
    "acronym": "FEN",
    "name": "Fernando de Noronha (FEN)",
    "nick": "Fernando de Noronha",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "FEN",
    "latitude": "-3.854679",
    "longitude": "-32.42165"
  },
  "PHL": {
    "id": "225",
    "acronym": "PHL",
    "name": "Filadelfia (PHL)",
    "nick": "Filadelfia",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "PHL",
    "latitude": "39.8743959",
    "longitude": "-75.2424229"
  },
  "FLN": {
    "id": "83",
    "acronym": "FLN",
    "name": "Florianopolis (FLN)",
    "nick": "Florianopolis",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "FLN",
    "latitude": "-27.670118",
    "longitude": "-48.5459657"
  },
  "FOR": {
    "id": "82",
    "acronym": "FOR",
    "name": "Fortaleza (FOR)",
    "nick": "Fortaleza",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "FOR",
    "latitude": "-3.7771555",
    "longitude": "-38.5330966"
  },
  "IGU": {
    "id": "81",
    "acronym": "IGU",
    "name": "Foz do Iguacu (IGU)",
    "nick": "Foz do Iguacu",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "IGU",
    "latitude": "-25.6002778",
    "longitude": "-54.485"
  },
  "FRA": {
    "id": "153",
    "acronym": "FRA",
    "name": "Frankfurt (FRA)",
    "nick": "Frankfurt",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "FRA",
    "latitude": "50.0379326",
    "longitude": "8.5621518"
  },
  "FNC": {
    "id": "192",
    "acronym": "FNC",
    "name": "Funchal (FNC)",
    "nick": "Funchal",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "FNC",
    "latitude": "32.6957983",
    "longitude": "-16.7758737"
  },
  "GVA": {
    "id": "130",
    "acronym": "GVA",
    "name": "Geneva (GVA)",
    "nick": "Geneva",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "GVA",
    "latitude": "46.2370946",
    "longitude": "6.1088432"
  },
  "GYN": {
    "id": "79",
    "acronym": "GYN",
    "name": "Goiania (GYN)",
    "nick": "Goiania",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "GYN",
    "latitude": "-16.632488",
    "longitude": "-49.2221166"
  },
  "GVR": {
    "id": "78",
    "acronym": "GVR",
    "name": "Gov. Valadares (GVR)",
    "nick": "Governador Valadares",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "GVR",
    "latitude": "-18.8975955",
    "longitude": "-41.9854826"
  },
  "HAM": {
    "id": "152",
    "acronym": "HAM",
    "name": "Hamburgo (HAM)",
    "nick": "Hamburgo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "HAM",
    "latitude": "53.633622",
    "longitude": "9.9974128"
  },
  "HAJ": {
    "id": "151",
    "acronym": "HAJ",
    "name": "Hanover (HAJ)",
    "nick": "Hanover",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "HAJ",
    "latitude": "52.4618486",
    "longitude": "9.6889919"
  },
  "IAH": {
    "id": "216",
    "acronym": "IAH",
    "name": "Houston George Bush Intl (IAH)",
    "nick": "Houston George Bush Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "IAH",
    "latitude": "29.9902199",
    "longitude": "-95.3367827"
  },
  "HUW": {
    "id": "251",
    "acronym": "HUW",
    "name": "Humaita (HUW)",
    "nick": "Humaita",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "HUW",
    "latitude": "-7.53222219",
    "longitude": "-63.0722222"
  },
  "IOS": {
    "id": "76",
    "acronym": "IOS",
    "name": "Ilheus (IOS)",
    "nick": "Ilheus",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "IOS",
    "latitude": "-14.8152123",
    "longitude": "-39.0317063"
  },
  "IMP": {
    "id": "75",
    "acronym": "IMP",
    "name": "Imperatriz (IMP)",
    "nick": "Imperatriz",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "IMP",
    "latitude": "-5.530341",
    "longitude": "-47.456497"
  },
  "IPN": {
    "id": "74",
    "acronym": "IPN",
    "name": "Ipatinga (IPN)",
    "nick": "Ipatinga",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "IPN",
    "latitude": "-19.4707569",
    "longitude": "-42.548012"
  },
  "IQQ": {
    "id": "144",
    "acronym": "IQQ",
    "name": "Iquique (IQQ)",
    "nick": "Iquique",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "IQQ",
    "latitude": "-20.535278",
    "longitude": "-70.181389"
  },
  "IQT": {
    "id": "188",
    "acronym": "IQT",
    "name": "Iquitos (IQT)",
    "nick": "Iquitos",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "IQT",
    "latitude": "-3.784722",
    "longitude": "-73.308611"
  },
  "ITB": {
    "id": "73",
    "acronym": "ITB",
    "name": "Itaituba (ITB)",
    "nick": "Itaituba",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "ITB",
    "latitude": "-4.2670701",
    "longitude": "-55.9931173"
  },
  "JAX": {
    "id": "215",
    "acronym": "JAX",
    "name": "Jacksonville (JAX)",
    "nick": "Jacksonville",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "JAX",
    "latitude": "30.4940713",
    "longitude": "-81.6879368"
  },
  "JPR": {
    "id": "72",
    "acronym": "JPR",
    "name": "Ji-Parana (JPR)",
    "nick": "Ji-Parana",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "JPR",
    "latitude": "-10.8746595",
    "longitude": "-61.8487562"
  },
  "JPA": {
    "id": "70",
    "acronym": "JPA",
    "name": "Joao Pessoa (JPA)",
    "nick": "Joao Pessoa",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "JPA",
    "latitude": "-7.1459413",
    "longitude": "-34.9515289"
  },
  "JOI": {
    "id": "69",
    "acronym": "JOI",
    "name": "Joinville (JOI)",
    "nick": "Joinville",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "JOI",
    "latitude": "-26.2233055",
    "longitude": "-48.8010274"
  },
  "JDO": {
    "id": "237",
    "acronym": "JDO",
    "name": "Juazeiro do Norte (JDO)",
    "nick": "Juazeiro do Norte",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "JDO",
    "latitude": "-7.2171164",
    "longitude": "-39.2726982"
  },
  "JDF": {
    "id": "68",
    "acronym": "JDF",
    "name": "Juiz de Fora (JDF)",
    "nick": "Juiz de Fora",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "JDF",
    "latitude": "-21.7844312",
    "longitude": "-43.3813451"
  },
  "JUL": {
    "id": "184",
    "acronym": "JUL",
    "name": "Juliaca (JUL)",
    "nick": "Juliaca",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "JUL",
    "latitude": "-15.4704701",
    "longitude": "-70.1565881"
  },
  "LSC": {
    "id": "137",
    "acronym": "LSC",
    "name": "La Serena (LSC)",
    "nick": "La Serena",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "LSC",
    "latitude": "-29.917297",
    "longitude": "-71.20369"
  },
  "LAS": {
    "id": "214",
    "acronym": "LAS",
    "name": "Las Vegas (LAS)",
    "nick": "Las Vegas",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "LAS",
    "latitude": "36.0839998",
    "longitude": "-115.1537389"
  },
  "LEC": {
    "id": "67",
    "acronym": "LEC",
    "name": "Lencois Chapada Diamantina (LEC)",
    "nick": "Lencois",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "LEC",
    "latitude": "-12.4837836",
    "longitude": "-41.275596"
  },
  "LIM": {
    "id": "183",
    "acronym": "LIM",
    "name": "Lima (LIM)",
    "nick": "Lima",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "LIM",
    "latitude": "-12.0240527",
    "longitude": "-77.112036"
  },
  "LIS": {
    "id": "191",
    "acronym": "LIS",
    "name": "Lisboa (LIS)",
    "nick": "Lisboa",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "LIS",
    "latitude": "38.7704",
    "longitude": "-9.1291"
  },
  "LHR": {
    "id": "167",
    "acronym": "LHR",
    "name": "Londres Heathrow Intl (LHR)",
    "nick": "Londres Heathrow Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "LHR",
    "latitude": "51.4700223",
    "longitude": "-0.4542955"
  },
  "LDB": {
    "id": "66",
    "acronym": "LDB",
    "name": "Londrina (LDB)",
    "nick": "Londrina",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "LDB",
    "latitude": "-23.3303126",
    "longitude": "-51.1382546"
  },
  "LAX": {
    "id": "213",
    "acronym": "LAX",
    "name": "Los Angeles (LAX)",
    "nick": "Los Angeles",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "LAX",
    "latitude": "33.9415889",
    "longitude": "-118.40853"
  },
  "MEA": {
    "id": "65",
    "acronym": "MEA",
    "name": "Macae (MEA)",
    "nick": "Macae",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "MEA",
    "latitude": "-22.3427461",
    "longitude": "-41.7655549"
  },
  "MCP": {
    "id": "64",
    "acronym": "MCP",
    "name": "Macapa (MCP)",
    "nick": "Macapa",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "MCP",
    "latitude": "0.0514099",
    "longitude": "-51.0696439"
  },
  "MCZ": {
    "id": "63",
    "acronym": "MCZ",
    "name": "Maceio (MCZ)",
    "nick": "Maceio",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "MCZ",
    "latitude": "-9.5129121",
    "longitude": "-35.7917733"
  },
  "MAD": {
    "id": "159",
    "acronym": "MAD",
    "name": "Madri Barajas Intl (MAD)",
    "nick": "Madri Barajas Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "MAD",
    "latitude": "40.4639597",
    "longitude": "-3.5700833"
  },
  "MAO": {
    "id": "62",
    "acronym": "MAO",
    "name": "Manaus (MAO)",
    "nick": "Manaus",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "MAO",
    "latitude": "-3.0358474",
    "longitude": "-60.0463249"
  },
  "MAB": {
    "id": "61",
    "acronym": "MAB",
    "name": "Maraba (MAB)",
    "nick": "Maraba",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "MAB",
    "latitude": "-5.3696095",
    "longitude": "-49.1384194"
  },
  "MII": {
    "id": "60",
    "acronym": "MII",
    "name": "Marilia (MII)",
    "nick": "Marilia",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "MII",
    "latitude": "-22.1970012",
    "longitude": "-49.9299134"
  },
  "MGF": {
    "id": "59",
    "acronym": "MGF",
    "name": "Maringa (MGF)",
    "nick": "Maringa",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "MGF",
    "latitude": "-23.4792013",
    "longitude": "-52.0123011"
  },
  "MDZ": {
    "id": "4",
    "acronym": "MDZ",
    "name": "Mendoza (MDZ)",
    "nick": "Mendoza",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "MDZ",
    "latitude": "-32.836924",
    "longitude": "-68.7944905"
  },
  "MIA": {
    "id": "212",
    "acronym": "MIA",
    "name": "Miami Miami Intl (MIA)",
    "nick": "Miami Miami Intl",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "MIA",
    "latitude": "25.796549",
    "longitude": "-80.275614"
  },
  "MXP": {
    "id": "172",
    "acronym": "MXP",
    "name": "Milao Malpensa Intl (MXP)",
    "nick": null,
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "MXP",
    "latitude": "45.6300625",
    "longitude": "8.7255307"
  },
  "MSP": {
    "id": "211",
    "acronym": "MSP",
    "name": "Minneapolis (MSP)",
    "nick": "Minneapolis",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "MSP",
    "latitude": "44.881234",
    "longitude": "-93.203111"
  },
  "MOC": {
    "id": "57",
    "acronym": "MOC",
    "name": "Montes Claros (MOC)",
    "nick": "Montes Claros",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "MOC",
    "latitude": "-16.7061431",
    "longitude": "-43.8192381"
  },
  "MVD": {
    "id": "230",
    "acronym": "MVD",
    "name": "Montevideo (MVD)",
    "nick": "Montevideo",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "MVD",
    "latitude": "-34.837778",
    "longitude": "-56.030278"
  },
  "YMQ": {
    "id": "125",
    "acronym": "YMQ",
    "name": "Montreal (YMQ)",
    "nick": "Montreal",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YMQ",
    "latitude": "45.510601",
    "longitude": "-73.714699"
  },
  "YUL": {
    "id": "128",
    "acronym": "YUL",
    "name": "Montreal (YUL)",
    "nick": "Montreal",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YUL",
    "latitude": "45.45764",
    "longitude": "-73.749697"
  },
  "MUC": {
    "id": "150",
    "acronym": "MUC",
    "name": "Munique (MUC)",
    "nick": "Munique",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "MUC",
    "latitude": "48.3536621",
    "longitude": "11.7750279"
  },
  "NAT": {
    "id": "56",
    "acronym": "NAT",
    "name": "Natal (NAT)",
    "nick": "Natal",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "NAT",
    "latitude": "-5.9051744",
    "longitude": "-35.2474118"
  },
  "NVT": {
    "id": "55",
    "acronym": "NVT",
    "name": "Navegantes (NVT)",
    "nick": "Navegantes",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "NVT",
    "latitude": "-26.8798437",
    "longitude": "-48.6508212"
  },
  "JFK": {
    "id": "210",
    "acronym": "JFK",
    "name": "Nova Iorque J.F. Kennedy Intl (JFK)",
    "nick": "Nova Iorque J.F. Kennedy Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "JFK",
    "latitude": "40.6413111",
    "longitude": "-73.7781391"
  },
  "LGA": {
    "id": "228",
    "acronym": "LGA",
    "name": "Nova Iorque La Guardia (LGA)",
    "nick": "Nova Iorque La Guardia",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "LGA",
    "latitude": "40.7769271",
    "longitude": "-73.8739659"
  },
  "NUE": {
    "id": "149",
    "acronym": "NUE",
    "name": "Nuremberg (NUE)",
    "nick": "Nuremberg",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "NUE",
    "latitude": "49.4971202",
    "longitude": "11.079808"
  },
  "MCO": {
    "id": "209",
    "acronym": "MCO",
    "name": "Orlando (MCO)",
    "nick": "Orlando",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "MCO",
    "latitude": "28.4311577",
    "longitude": "-81.308083"
  },
  "OSL": {
    "id": "176",
    "acronym": "OSL",
    "name": "Oslo (OSL)",
    "nick": "Oslo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "OSL",
    "latitude": "60.1975501",
    "longitude": "11.1004153"
  },
  "ZOS": {
    "id": "136",
    "acronym": "ZOS",
    "name": "Osorno (ZOS)",
    "nick": "Osorno",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ZOS",
    "latitude": "-40.611389",
    "longitude": "-73.060556"
  },
  "YOW": {
    "id": "124",
    "acronym": "YOW",
    "name": "Ottawa (YOW)",
    "nick": "Ottawa",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YOW",
    "latitude": "45.319212",
    "longitude": "-75.6691652"
  },
  "PMW": {
    "id": "54",
    "acronym": "PMW",
    "name": "Palmas (PMW)",
    "nick": "Palmas",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "PMW",
    "latitude": "-10.2929366",
    "longitude": "-48.3565057"
  },
  "PIN": {
    "id": "53",
    "acronym": "PIN",
    "name": "Parintins (PIN)",
    "nick": "Parintins",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "PIN",
    "latitude": "-2.6377762",
    "longitude": "-56.7295262"
  },
  "CDG": {
    "id": "165",
    "acronym": "CDG",
    "name": "Paris Charles de Gaulle Intl (CDG)",
    "nick": "Paris Charles de Gaulle Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "CDG",
    "latitude": "49.004",
    "longitude": "2.5711"
  },
  "PFB": {
    "id": "52",
    "acronym": "PFB",
    "name": "Passo Fundo (PFB)",
    "nick": "Passo Fundo",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "PFB",
    "latitude": "-28.242583",
    "longitude": "-52.3298287"
  },
  "POJ": {
    "id": "116",
    "acronym": "POJ",
    "name": "Patos de Minas (POJ)",
    "nick": "Patos de Minas",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "POJ",
    "latitude": "-18.6718417",
    "longitude": "-46.4925779"
  },
  "PET": {
    "id": "51",
    "acronym": "PET",
    "name": "Pelotas (PET)",
    "nick": "Pelotas",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "PET",
    "latitude": "-31.7176791",
    "longitude": "-52.3327361"
  },
  "PEK": {
    "id": "146",
    "acronym": "PEK",
    "name": "Pequim (PEK)",
    "nick": "Pequim",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "PEK",
    "latitude": "40.0798573",
    "longitude": "116.6031121"
  },
  "PNZ": {
    "id": "50",
    "acronym": "PNZ",
    "name": "Petrolina (PNZ)",
    "nick": "Petrolina",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "PNZ",
    "latitude": "-9.3671189",
    "longitude": "-40.5661312"
  },
  "PHX": {
    "id": "208",
    "acronym": "PHX",
    "name": "Phoenix (PHX)",
    "nick": "Phoenix",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "PHX",
    "latitude": "33.4372686",
    "longitude": "-112.0077881"
  },
  "PIU": {
    "id": "182",
    "acronym": "PIU",
    "name": "Piura (PIU)",
    "nick": "Piura",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "PIU",
    "latitude": "-5.2061618",
    "longitude": "-80.6184056"
  },
  "PDX": {
    "id": "207",
    "acronym": "PDX",
    "name": "Portland (PDX)",
    "nick": "Portland",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "PDX",
    "latitude": "45.5897694",
    "longitude": "-122.5950942"
  },
  "OPO": {
    "id": "190",
    "acronym": "OPO",
    "name": "Porto (OPO)",
    "nick": "Porto",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "OPO",
    "latitude": "41.2421186",
    "longitude": "-8.6785514"
  },
  "POA": {
    "id": "49",
    "acronym": "POA",
    "name": "Porto Alegre (POA)",
    "nick": "Porto Alegre",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "POA",
    "latitude": "-29.9934732",
    "longitude": "-51.1753811"
  },
  "PXO": {
    "id": "189",
    "acronym": "PXO",
    "name": "Porto Santo (PXO)",
    "nick": "Porto Santo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "PXO",
    "latitude": "33.074929",
    "longitude": "-16.3501883"
  },
  "BPS": {
    "id": "48",
    "acronym": "BPS",
    "name": "Porto Seguro (BPS)",
    "nick": "Porto Seguro",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "BPS",
    "latitude": "-16.4388018",
    "longitude": "-39.0802335"
  },
  "PVH": {
    "id": "46",
    "acronym": "PVH",
    "name": "Porto Velho (PVH)",
    "nick": "Porto Velho",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "PVH",
    "latitude": "-8.7148077",
    "longitude": "-63.9011504"
  },
  "PPB": {
    "id": "45",
    "acronym": "PPB",
    "name": "Presidente Prudente (PPB)",
    "nick": "Presidente Prudente",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "PPB",
    "latitude": "-22.1775105",
    "longitude": "-51.4187132"
  },
  "PCL": {
    "id": "181",
    "acronym": "PCL",
    "name": "Pucallpa (PCL)",
    "nick": "Pucallpa",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "PCL",
    "latitude": "-8.3775337",
    "longitude": "-74.5740366"
  },
  "PEM": {
    "id": "180",
    "acronym": "PEM",
    "name": "Puerto Maldonado (PEM)",
    "nick": "Puerto Maldonado",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "PEM",
    "latitude": "-12.612272",
    "longitude": "-69.228756"
  },
  "PMC": {
    "id": "135",
    "acronym": "PMC",
    "name": "Puerto Montt (PMC)",
    "nick": "Puerto Montt",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "PMC",
    "latitude": "-41.438889",
    "longitude": "-73.093889"
  },
  "PUQ": {
    "id": "134",
    "acronym": "PUQ",
    "name": "Punta Arenas (PUQ)",
    "nick": "Punta Arenas",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "PUQ",
    "latitude": "-53.003611",
    "longitude": "-70.853611"
  },
  "PUJ": {
    "id": "239",
    "acronym": "PUJ",
    "name": "Punta Cana (PUJ)",
    "nick": "Punta Cana",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "PUJ",
    "latitude": "18.562998",
    "longitude": "-68.363617"
  },
  "PDP": {
    "id": "229",
    "acronym": "PDP",
    "name": "Punta Del Este (PDP)",
    "nick": "Punta Del Este",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "PDP",
    "latitude": "-34.8551135",
    "longitude": "-55.0946958"
  },
  "YQB": {
    "id": "123",
    "acronym": "YQB",
    "name": "Quebec (YQB)",
    "nick": "Quebec",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YQB",
    "latitude": "46.7907719",
    "longitude": "-71.388569"
  },
  "RDU": {
    "id": "206",
    "acronym": "RDU",
    "name": "Raleigh Durham (RDU)",
    "nick": "Raleigh Durham",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "RDU",
    "latitude": "35.880079",
    "longitude": "-78.7879963"
  },
  "REC": {
    "id": "44",
    "acronym": "REC",
    "name": "Recife (REC)",
    "nick": "Recife",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "REC",
    "latitude": "-8.1259315",
    "longitude": "-34.9240154"
  },
  "REZ": {
    "id": "253",
    "acronym": "REZ",
    "name": "Resende (REZ)",
    "nick": "Resende",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "REZ",
    "latitude": "-22.4780556",
    "longitude": "-44.4811111"
  },
  "RAO": {
    "id": "43",
    "acronym": "RAO",
    "name": "Ribeirao Preto (RAO)",
    "nick": "Ribeirao Preto",
    "azul": true,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "RAO",
    "latitude": "-21.134161",
    "longitude": "-47.773637"
  },
  "RBR": {
    "id": "42",
    "acronym": "RBR",
    "name": "Rio Branco (RBR)",
    "nick": "Rio Branco",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "RBR",
    "latitude": "-9.8689586",
    "longitude": "-67.8959112"
  },
  "GIG": {
    "id": "41",
    "acronym": "GIG",
    "name": "Rio de Janeiro - Galeao Intl (GIG)",
    "nick": "Galeao",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "GIG",
    "latitude": "-22.8134098",
    "longitude": "-43.2494233"
  },
  "SDU": {
    "id": "40",
    "acronym": "SDU",
    "name": "Rio de Janeiro - Santos Dumont (SDU)",
    "nick": "Santos Drumont",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "SDU",
    "latitude": "-22.9111438",
    "longitude": "-43.1648755"
  },
  "RIO": {
    "id": "39",
    "acronym": "RIO",
    "name": "Rio de Janeiro - Todos (RIO)",
    "nick": "Rio de Janeiro - Todos",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "RIO,SDU,GIG",
    "latitude": null,
    "longitude": null
  },
  "RGL": {
    "id": "3",
    "acronym": "RGL",
    "name": "Rio Gallegos (RGL)",
    "nick": "Rio Gallegos",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "RGL",
    "latitude": "-51.608889",
    "longitude": "-69.312778"
  },
  "RVD": {
    "id": "115",
    "acronym": "RVD",
    "name": "Rio Verde (RVD)",
    "nick": "Rio Verde",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "RVD",
    "latitude": "-17.8359091",
    "longitude": "-50.9588563"
  },
  "ROO": {
    "id": "37",
    "acronym": "ROO",
    "name": "Rondonopolis (ROO)",
    "nick": "Rondonopolis",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "ROO",
    "latitude": "-16.585278",
    "longitude": "-54.724167"
  },
  "ROS": {
    "id": "240",
    "acronym": "ROS",
    "name": "Rosario (ROS)",
    "nick": "Rosario",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "ROS",
    "latitude": "-32.9206311",
    "longitude": "-60.7823156"
  },
  "SLC": {
    "id": "205",
    "acronym": "SLC",
    "name": "Salt Lake City (SLC)",
    "nick": "Salt Lake City",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SLC",
    "latitude": "40.785596",
    "longitude": "-111.980673"
  },
  "SLA": {
    "id": "2",
    "acronym": "SLA",
    "name": "Salta (SLA)",
    "nick": "Salta",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SLA",
    "latitude": "-24.8442777",
    "longitude": "-65.4787676"
  },
  "SSA": {
    "id": "36",
    "acronym": "SSA",
    "name": "Salvador (SSA)",
    "nick": "Sao Salvador",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "SSA",
    "latitude": "-12.9110977",
    "longitude": "-38.3312411"
  },
  "SAN": {
    "id": "226",
    "acronym": "SAN",
    "name": "San Diego San Diego Intl (SAN)",
    "nick": "San Diego San Diego Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "SAN",
    "latitude": "32.7319",
    "longitude": "-117.197312"
  },
  "SFO": {
    "id": "203",
    "acronym": "SFO",
    "name": "San Francisco (SFO)",
    "nick": "San Francisco",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SFO",
    "latitude": "37.615223",
    "longitude": "-122.389979"
  },
  "SJC": {
    "id": "202",
    "acronym": "SJC",
    "name": "San Jose (SJC)",
    "nick": "San Jose",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "SJC",
    "latitude": "37.366695",
    "longitude": "-121.925906"
  },
  "VVI": {
    "id": "13",
    "acronym": "VVI",
    "name": "Santa Cruz de la Sierra (VVI)",
    "nick": "Santa Cruz de la Sierra",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "VVI",
    "latitude": "-17.8055975",
    "longitude": "-63.1781761"
  },
  "IRZ": {
    "id": "254",
    "acronym": "IRZ",
    "name": "Santa Isabel do Rio Negro (IRZ)",
    "nick": "Santa Isabel do Rio Negro",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "IRZ",
    "latitude": "-0.4169444",
    "longitude": "-65.0338889"
  },
  "RIA": {
    "id": "35",
    "acronym": "RIA",
    "name": "Santa Maria (RIA)",
    "nick": "Santa Maria",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "RIA",
    "latitude": "-29.7103555",
    "longitude": "-53.6914195"
  },
  "STM": {
    "id": "33",
    "acronym": "STM",
    "name": "Santarem (STM)",
    "nick": "Santarem",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "STM",
    "latitude": "-2.4241016",
    "longitude": "-54.7864538"
  },
  "SCL": {
    "id": "133",
    "acronym": "SCL",
    "name": "Santiago (SCL)",
    "nick": "Santiago",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SCL",
    "latitude": "-33.3892492",
    "longitude": "-70.7944216"
  },
  "SDQ": {
    "id": "241",
    "acronym": "SDQ",
    "name": "Santo Domingo (SDQ)",
    "nick": "Santo Domingo",
    "azul": false,
    "gol": true,
    "tam": false,
    "avianca": false,
    "combination": "SDQ",
    "latitude": "18.4302194",
    "longitude": "-69.6764909"
  },
  "SJL": {
    "id": "255",
    "acronym": "SJL",
    "name": "Sao Gabriel da Cachoeira (SJL)",
    "nick": "Sao Gabriel da Cachoeira",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "SJL",
    "latitude": "0.118611",
    "longitude": "-67.084722"
  },
  "JDR": {
    "id": "256",
    "acronym": "JDR",
    "name": "Sao Joao del-Rei (JDR)",
    "nick": "Sao Joao del-Rei",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "JDR",
    "latitude": "-21.0853596",
    "longitude": "-44.2239241"
  },
  "SJP": {
    "id": "31",
    "acronym": "SJP",
    "name": "Sao Jose do Rio Preto (SJP)",
    "nick": "Sao Jose do Rio Preto",
    "azul": true,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SJP",
    "latitude": "-20.811824",
    "longitude": "-49.4046721"
  },
  "SJK": {
    "id": "30",
    "acronym": "SJK",
    "name": "Sao Jose dos Campos (SJK)",
    "nick": "Sao Jose dos Campos",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "SJK",
    "latitude": "-23.2267859",
    "longitude": "-45.8626332"
  },
  "SLZ": {
    "id": "29",
    "acronym": "SLZ",
    "name": "Sao Luis (SLZ)",
    "nick": "Sao Luis",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "SLZ",
    "latitude": "-2.5871416",
    "longitude": "-44.2369198"
  },
  "CPQ": {
    "id": "242",
    "acronym": "CPQ",
    "name": "Sao Paulo - Campinas (CPQ)",
    "nick": "Viracopos",
    "azul": false,
    "gol": true,
    "tam": true,
    "avianca": false,
    "combination": "CPQ,VCP",
    "latitude": "-22.8593154",
    "longitude": "-47.1099117"
  },
  "CGH": {
    "id": "28",
    "acronym": "CGH",
    "name": "Sao Paulo - Congonhas (CGH)",
    "nick": "Congonhas",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "CGH",
    "latitude": "-23.6273246",
    "longitude": "-46.6565842"
  },
  "GRU": {
    "id": "27",
    "acronym": "GRU",
    "name": "Sao Paulo - Guarulhos Intl (GRU)",
    "nick": "Guarulhos",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "GRU",
    "latitude": "-23.4345529",
    "longitude": "-46.478126"
  },
  "SAO": {
    "id": "25",
    "acronym": "SAO",
    "name": "Sao Paulo - Todos (SAO)",
    "nick": "Sao Paulo - Todos",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "GRU,CGH,VCP,CPQ",
    "latitude": null,
    "longitude": null
  },
  "OLC": {
    "id": "257",
    "acronym": "OLC",
    "name": "Sao Paulo de Olivenca (OLC)",
    "nick": "Sao Paulo de Olivenca",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": false,
    "combination": "OLC",
    "latitude": "-3.4655556",
    "longitude": "-68.9188889"
  },
  "SEA": {
    "id": "201",
    "acronym": "SEA",
    "name": "Seattle Tacoma Intl (SEA)",
    "nick": "Seattle Tacoma Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "SEA",
    "latitude": "47.44443",
    "longitude": "-122.300497"
  },
  "OPS": {
    "id": "24",
    "acronym": "OPS",
    "name": "Sinop (OPS)",
    "nick": "Sinop",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "OPS",
    "latitude": "-11.8347335",
    "longitude": "-55.4979097"
  },
  "STR": {
    "id": "148",
    "acronym": "STR",
    "name": "Stuttgart Stuttgart Intl (STR)",
    "nick": "Stuttgart Stuttgart Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "STR",
    "latitude": "48.6876365",
    "longitude": "9.205576"
  },
  "TBT": {
    "id": "114",
    "acronym": "TBT",
    "name": "Tabatinga (TBT)",
    "nick": "Tabatinga",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "TBT",
    "latitude": "-4.2530285",
    "longitude": "-69.9389151"
  },
  "TCQ": {
    "id": "179",
    "acronym": "TCQ",
    "name": "Tacna (TCQ)",
    "nick": "Tacna",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "TCQ",
    "latitude": "-18.053056",
    "longitude": "-70.275556"
  },
  "TPA": {
    "id": "200",
    "acronym": "TPA",
    "name": "Tampa (TPA)",
    "nick": "Tampa",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "TPA",
    "latitude": "27.976891",
    "longitude": "-82.533377"
  },
  "TPP": {
    "id": "178",
    "acronym": "TPP",
    "name": "Tarapoto (TPP)",
    "nick": "Tarapoto",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "TPP",
    "latitude": "-6.508889",
    "longitude": "-76.373333"
  },
  "TFF": {
    "id": "113",
    "acronym": "TFF",
    "name": "Tefe (TFF)",
    "nick": "Tefe",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "TFF",
    "latitude": "-3.380402",
    "longitude": "-64.7250955"
  },
  "ZCO": {
    "id": "132",
    "acronym": "ZCO",
    "name": "Temuco (ZCO)",
    "nick": "Temuco",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ZCO",
    "latitude": "-38.766944",
    "longitude": "-72.637222"
  },
  "THE": {
    "id": "23",
    "acronym": "THE",
    "name": "Teresina (THE)",
    "nick": "Teresina",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "THE",
    "latitude": "-5.0630809",
    "longitude": "-42.8224831"
  },
  "NRT": {
    "id": "173",
    "acronym": "NRT",
    "name": "Toquio Narita Intl (NRT)",
    "nick": "Toquio Narita Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "NRT",
    "latitude": "35.7632359",
    "longitude": "140.385194"
  },
  "YYZ": {
    "id": "122",
    "acronym": "YYZ",
    "name": "Toronto (YYZ)",
    "nick": "Toronto",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YYZ",
    "latitude": "43.681727",
    "longitude": "-79.612049"
  },
  "TMT": {
    "id": "47",
    "acronym": "TMT",
    "name": "Trombetas (TMT)",
    "nick": "Trombetas",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "TMT",
    "latitude": "-1.489959",
    "longitude": "-56.396162"
  },
  "TRU": {
    "id": "177",
    "acronym": "TRU",
    "name": "Trujillo (TRU)",
    "nick": "Trujillo",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "TRU",
    "latitude": "-8.0818881",
    "longitude": "-79.1082784"
  },
  "TUR": {
    "id": "22",
    "acronym": "TUR",
    "name": "Tucurui (TUR)",
    "nick": "Tucurui",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "TUR",
    "latitude": "-3.7660765",
    "longitude": "-49.6777695"
  },
  "UBA": {
    "id": "21",
    "acronym": "UBA",
    "name": "Uberaba (UBA)",
    "nick": "Uberaba",
    "azul": true,
    "gol": true,
    "tam": false,
    "avianca": true,
    "combination": "UBA",
    "latitude": "-19.766328",
    "longitude": "-47.9661859"
  },
  "UDI": {
    "id": "20",
    "acronym": "UDI",
    "name": "Uberlandia (UDI)",
    "nick": "Uberlandia",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "UDI",
    "latitude": "-18.8877834",
    "longitude": "-48.2312674"
  },
  "USH": {
    "id": "1",
    "acronym": "USH",
    "name": "Ushuaia (USH)",
    "nick": "Ushuaia",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "USH",
    "latitude": "-54.843333",
    "longitude": "-68.295556"
  },
  "ZAL": {
    "id": "131",
    "acronym": "ZAL",
    "name": "Valdivia (ZAL)",
    "nick": "Valdivia",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ZAL",
    "latitude": "-39.796944",
    "longitude": "-73.241669"
  },
  "YVR": {
    "id": "121",
    "acronym": "YVR",
    "name": "Vancouver (YVR)",
    "nick": "Vancouver",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YVR",
    "latitude": "49.1966913",
    "longitude": "-123.1815123"
  },
  "VAG": {
    "id": "119",
    "acronym": "VAG",
    "name": "Varginha (VAG)",
    "nick": "Varginha",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "VAG",
    "latitude": "-21.5762527",
    "longitude": "-45.4575472"
  },
  "VIE": {
    "id": "11",
    "acronym": "VIE",
    "name": "Vienna (VIE)",
    "nick": "Vienna",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "VIE",
    "latitude": "48.1158333",
    "longitude": "16.5665751"
  },
  "BVH": {
    "id": "17",
    "acronym": "BVH",
    "name": "Vilhena (BVH)",
    "nick": "Vilhena",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "BVH",
    "latitude": "-12.6897785",
    "longitude": "-60.1004876"
  },
  "VIX": {
    "id": "16",
    "acronym": "VIX",
    "name": "Vitoria (VIX)",
    "nick": "Vitoria",
    "azul": true,
    "gol": true,
    "tam": true,
    "avianca": true,
    "combination": "VIX",
    "latitude": "-20.2576489",
    "longitude": "-40.2835346"
  },
  "VDC": {
    "id": "15",
    "acronym": "VDC",
    "name": "Vitoria da Conquista (VDC)",
    "nick": "Vitoria da Conquista",
    "azul": true,
    "gol": false,
    "tam": false,
    "avianca": true,
    "combination": "VDC",
    "latitude": "-14.863611",
    "longitude": "-40.863056"
  },
  "IAD": {
    "id": "198",
    "acronym": "IAD",
    "name": "Washington Dulles Intl (IAD)",
    "nick": "Washington Dulles Intl",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "IAD",
    "latitude": "38.953381",
    "longitude": "-77.447712"
  },
  "DCA": {
    "id": "227",
    "acronym": "DCA",
    "name": "Washington Ronald Reagan National (DCA)",
    "nick": "Washington Ronald Reagan National",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": false,
    "combination": "DCA",
    "latitude": "38.851242",
    "longitude": "-77.0402315"
  },
  "YWG": {
    "id": "120",
    "acronym": "YWG",
    "name": "Winnipeg (YWG)",
    "nick": "Winnipeg",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "YWG",
    "latitude": "49.904033",
    "longitude": "-97.22588"
  },
  "ZRH": {
    "id": "129",
    "acronym": "ZRH",
    "name": "Zurique (ZRH)",
    "nick": "Zurique",
    "azul": false,
    "gol": false,
    "tam": true,
    "avianca": true,
    "combination": "ZRH",
    "latitude": "47.4504",
    "longitude": "8.5619"
  }
};